name: Deploy to AKS

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: vareladavid/nginx-aksperso:v1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

    - name: Deploy to AKS
      run: |
        kubectl apply -f nginx-deployment.yaml
